---
title: "Detailed analysis"
output:
  html_document:
    toc: yes
    toc_float: yes
date: 'Last updated: `r format.Date(Sys.Date(), "%d %B %Y")`'
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, out.width = '100%')
library(htmltools)

for (script in list.files("scripts", full.names = TRUE)) {
  source(script)
}
```

<PLACEHOLDER FOR TEXT>

## The Four harms

<PLACEHOLDER FOR TEXT>

### 1. Direct health harms

<PLACEHOLDER FOR TEXT>

```{r}

get_text(worksheet = "R",
         column = "headline") %>%
  h4()

get_text(worksheet = "R",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "R",
         column = "summary_max_30_words") %>%
  p()

plots[["1r"]]


get_text(worksheet = "R",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "R",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "R",
         column = "methodology") %>%
    paste("Methodology:", .) %>%
  p()

```

```{r}

get_text(worksheet = "Infectious_people",
         column = "headline") %>%
  h4()

get_text(worksheet = "Infectious_people",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "Infectious_people",
         column = "summary_max_30_words") %>%
  p()

plots[["1_infect"]]


get_text(worksheet = "Infectious_people",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "Infectious_people",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "Infectious_people",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()

```


#### Cases

<PLACEHOLDER FOR TEXT>

```{r}
plots[["1_cases"]]
```

<PLACEHOLDER FOR TEXT>

#### Deaths

<PLACEHOLDER FOR TEXT>
```{r}
plots[["1a"]]
```
<button class="btn btn-link" data-toggle="collapse" data-target="#BlockName"> Show more
<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
</button>  
<div id="BlockName" class="collapse">  

##### Source

<PLACEHOLDER FOR TEXT>

##### Methodology

<PLACEHOLDER FOR TEXT>

##### Assumptions

<PLACEHOLDER FOR TEXT>

</div>

<PLACEHOLDER FOR TEXT>

#### Deaths by setting

<PLACEHOLDER FOR TEXT>

```{r}
plots[["1b"]]
```

<PLACEHOLDER FOR TEXT>

#### People in hospital with COVID-19

<PLACEHOLDER FOR TEXT>

```{r}
plots[["1c"]]
```

<PLACEHOLDER FOR TEXT>

### 2. Indirect health harms

#### A&E attendance

<PLACEHOLDER FOR TEXT>

```{r}
plots[["2a"]]
```

#### Excess mortality

<PLACEHOLDER FOR TEXT>

```{r}
plots[["2_excess"]]
```

#### Emergency and planned admissions

<PLACEHOLDER FOR TEXT>

```{r}
plots[["2_admissions"]]
```

```{r}
get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "headline") %>%
  h4()

get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "summary_max_30_words") %>%
  p()

plots[["2_GP"]]

get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "Avoiding_GPs&Hospitals",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

### 3. Societal harms

#### Vulnerable children at school 


<PLACEHOLDER FOR TEXT>

```{r}
plots[["3a"]]
```

<PLACEHOLDER FOR TEXT>

```{r}
get_text(worksheet = "data_crisis_applications",
         column = "headline") %>%
  h4()

get_text(worksheet = "data_crisis_applications",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "data_crisis_applications",
         column = "summary_max_30_words") %>%
  p()

plots[["3_crisis_applications"]]

get_text(worksheet = "data_crisis_applications",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "data_crisis_applications",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "data_crisis_applications",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

<PLACEHOLDER FOR TEXT>

```{r}
get_text(worksheet = "data_recorded_crime",
         column = "headline") %>%
  h4()

get_text(worksheet = "data_recorded_crime",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "data_recorded_crime",
         column = "summary_max_30_words") %>%
  p()

plots[["3_crime"]]

get_text(worksheet = "data_recorded_crime",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "data_recorded_crime",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "data_recorded_crime",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

```{r}
get_text(worksheet = "Loneliness",
         column = "headline") %>%
  h4()

get_text(worksheet = "Loneliness",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "Loneliness",
         column = "summary_max_30_words") %>%
  p()

plots[["3_loneliness"]]

get_text(worksheet = "Loneliness",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "Loneliness",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "Loneliness",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

```{r}
get_text(worksheet = "Trust_In_Government_(SG)",
         column = "headline") %>%
  h4()

get_text(worksheet = "Trust_In_Government_(SG)",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "Trust_In_Government_(SG)",
         column = "summary_max_30_words") %>%
  p()

plots[["3_trust"]]

get_text(worksheet = "Trust_In_Government_(SG)",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "Trust_In_Government_(SG)",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "Trust_In_Government_(SG)",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

```{r}
get_text(worksheet = "Threat_To_Job",
         column = "headline") %>%
  h4()

get_text(worksheet = "Threat_To_Job",
         column = "next_update") %>%
  format("%d %B %Y") %>%
  paste("Next update:", .) %>%
  p()

get_text(worksheet = "Threat_To_Job",
         column = "summary_max_30_words") %>%
  p()

plots[["3_job"]]

get_text(worksheet = "Threat_To_Job",
         column = "discussion_max_100_words") %>%
  p()

get_text(worksheet = "Threat_To_Job",
         column = "source") %>%
  paste("Source:", .) %>%
  p()

get_text(worksheet = "Threat_To_Job",
         column = "methodology") %>%
  paste("Methodology:", .) %>%
  p()
```

### 4. Economic harms

#### Universal credit claims
```{r}
plots[["4a"]]
```

#### Economic harm 2
#### Economic harm 3