---
title: "COVID-19 in Scotland"
output: html_document
date: 'Last updated: `r format.Date(Sys.Date(), "%d %B %Y")`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(htmltools)
library(tidyr)

for (script in list.files("scripts", full.names = TRUE)) {
  source(script)
}
```

```{r}
narrative %>%
  filter(harm == 0, section == "Introduction") %>%
  pull("text") %>%
  create_html()
  
htmltools::hr(style="height:2px;border-width:0;color:#8e979c;background-color:#8e979c")
```

```{r}
div(class = "row fluid-row text-center",
    div(class = "col-md-6",
        a(href="summary.html",
          img(src="images/navigation_summary.svg", style="width: 90%;", alt="The four harms of Covid-19: direct health, indirect health, society, economy")),
        a(href="summary.html", h3("Visual summary")),
        p("Click on here to see an overview of the four harms")),
    div(class = "col-md-6",
        a(href="detail.html",
          img(src="images/navigation_detail.svg", style="width: 90%;", alt="A rough sketch of a chart and text")),
    a(href="detail.html", h3("Detailed analysis")),
    p("Click on here to explore the four harms")))

htmltools::hr(style="height:2px;border-width:0;color:#8e979c;background-color:#8e979c")
```

```{r}
div(class = "row fluid-row",
    div(class = "col-md-6", div(
      class = "panel panel-default",
      div(class = "panel-heading",
          h3(class = "panel-title", a("Direct health impacts", href = "detail.html#1_direct_health_harms"))),
      div(class = "panel-body", narrative %>% 
  filter(harm == 1, section == "Definition") %>% 
  pull("text") %>%
  create_html())
    )),
    div(class = "col-md-6", div(
      class = "panel panel-default",
      div(class = "panel-heading",
          h3(class = "panel-title", a("Health harms not directly related to COVID-19", href = "detail.html#2_indirect_health_harms"))),
      div(class = "panel-body", narrative %>% 
  filter(harm == 2, section == "Definition") %>% 
  pull("text") %>%
  create_html())
    )))


div(class = "row fluid-row",
    div(class = "col-md-6", div(
      class = "panel panel-default",
      div(class = "panel-heading",
          h3(class = "panel-title", a("Societal impacts", href = "detail.html#3_societal_harms"))),
      div(class = "panel-body", narrative %>% 
  filter(harm == 3, section == "Definition") %>% 
  pull("text") %>%
  create_html())
    )),
    div(class = "col-md-6", div(
      class = "panel panel-default",
      div(class = "panel-heading",
          h3(class = "panel-title", a("Economic impacts", href = "detail.html#4_economic_harms"))),
      div(class = "panel-body", narrative %>% 
  filter(harm == 4, section == "Definition") %>% 
  pull("text") %>%
  create_html())
    )))
```

```{r}
  narrative %>%
  filter(harm == 0, section == "Introduction_2") %>%
  pull("text") %>%
  create_html()
```
